# https://prettier.io/docs/options
printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
jsxSingleQuote: false
quoteProps: preserve
trailingComma: es5
bracketSpacing: true
objectWrap: preserve
bracketSameLine: false
arrowParens: always
