packages:
  - chart
  - i18n
  - frontend
  - route
  - worker

allowBuilds:
  '@google/genai': true
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  core-js: false
  esbuild: true
  protobufjs: false
  sharp: true
  unrs-resolver: true

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  # these are authored by me (@na-trium-144)
  - fn-commands
  - next-license-list

dedupePeers: true
verifyDepsBeforeRun: warn

# change this to hoisted only when deploying to vercel
nodeLinker: isolated
