import { HashSchema } from "@falling-nikochan/chart";
import * as v from "valibot";

export const plainPasswdHeaderDoc = {
  name: "Authorization",
  in: "header",
  description: "`Nikochan-Basic (base64 encode of plain password)`",
  schema: { type: "string" },
} as const;
export const passwdHeaderDoc = {
  name: "Authorization",
  in: "header",
  description:
    "Either `Nikochan-Basic (base64 encode of plain password)`, " +
    "`Nikochan-Hash (hashed password)` or `Nikochan-Bypass (any string)`.",
  schema: { type: "string" },
} as const;

export const PlainPasswdParamSchema = () =>
  v.pipe(v.string(), v.minLength(1), v.description("plain password"));
export const PasswdParamSchema = () =>
  v.object({
    p: v.optional(PlainPasswdParamSchema()),
    ph: v.optional(
      v.pipe(
        HashSchema(),
        v.description(
          "Hashed password generated by /api/hashPasswd. pUserSalt cookie must be set."
        )
      )
    ),
    pbypass: v.optional(v.string()),
  });

type PasswdParams = v.InferOutput<ReturnType<typeof PasswdParamSchema>>;

export function getPasswdParamsFromAuthHeader(
  authorization: string | undefined
): PasswdParams | undefined {
  if (!authorization) {
    return undefined;
  }

  const { Authorization: authParams } = v.parse(
    v.object({
      Authorization: v.strictObject({
        "Nikochan-Basic": v.optional(v.pipe(v.string(), v.base64())),
        "Nikochan-Hash": v.optional(HashSchema()),
        "Nikochan-Bypass": v.optional(v.string()),
      }),
    }),
    { Authorization: Object.fromEntries([authorization.split(" ")]) }
  );
  if (authParams["Nikochan-Basic"]) {
    return {
      p: new TextDecoder().decode(
        Buffer.from(authParams["Nikochan-Basic"], "base64")
      ),
    };
  }
  if (authParams["Nikochan-Hash"]) {
    return { ph: authParams["Nikochan-Hash"] };
  }
  if (authParams["Nikochan-Bypass"]) {
    return { pbypass: authParams["Nikochan-Bypass"] };
  }
  return undefined;
}
