import type { Metadata } from "next";
import "./globals.css";
import { AutoScaler } from "./scale";

export const metadata: Metadata = {
  title: "FallingNikochan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <AutoScaler>{children}</AutoScaler>
      </body>
    </html>
  );
}
