import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "FallingNikochan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-t from-white to-sky-200 ">
        {children}
      </body>
    </html>
  );
}
