name: Purge Cloudflare Cache
on:
  push:
    branches: [ "main" ]
jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
    - name: Wait 2 min before Vercel builds
      run: sleep 120
    - name: Purge Cloudflare Cache
      run: >
        curl https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache
        -H 'Content-Type: application/json'
        -H "Authorization: Bearer $CLOUDFLARE_API_KEY"
        -d '{"purge_everything":true}'
      env:
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
